
const dataObject = {
    dataIdentity : [
      "You are a radiant light", "Your presence is a profound gift", "You are an essential thread in the tapestry of life",
      "Your soul is a masterpiece of resilience", "You are a person of incredible value", "Your heart is a sanctuary of kindness",
      "You are a vital spark in this universe", "Your journey is a testament to strength", "You are a unique and unrepeatable wonder",
      "Your existence is a beautiful necessity", "You are a source of untapped potential", "Your inner world is a vast landscape of beauty",
      "You are a beacon of hope for those around you", "Your spirit is crafted with infinite care", "You are a courageous soul",
      "Your life is a story of quiet triumph", "You are a vessel of compassion", "Your mind is a garden of brilliant ideas",
      "You are a force of nature and grace", "Your very breath is a miracle", "You are a cornerstone of strength for others",
      "Your authenticity is a rare treasure", "You are a champion of your own story", "Your kindness is a powerful legacy",
      "You are a reflection of the universe's creativity", "Your empathy is a healing force", "You are a steady hand in a changing world",
      "Your laughter is a melody the world needs", "You are a warrior of light and love", "Your perspective is an invaluable asset",
      "You are a brilliant architect of your future", "Your love is a transformative power", "You are a symbol of endurance",
      "Your voice is a necessary harmony", "You are a vessel of wisdom", "Your character is a fortress of integrity",
      "You are a pioneer of your own path", "Your sensitivity is a profound strength", "You are a bright star in a vast sky",
      "Your spirit is an anchor for many", "You are a carrier of peace", "Your curiosity is a gateway to greatness",
      "Your energy is a gift to the earth", "You are a living example of courage", "Your patience is a form of deep wisdom",
      "You are a light that cannot be dimmed", "Your passion is a spark for change", "You are a masterpiece in progress",
      "Your heart is a reservoir of courage", "You are a bridge between hope and reality", "Your silence is as powerful as your speech",
      "You are a miracle of biological and spiritual design", "Your resilience is a guiding light", "You are a necessary part of the whole",
      "Your growth is a sacred process", "You are a weaver of dreams", "Your intuition is a reliable compass",
      "Your warmth is a shelter for the weary", "You are a seeker of truth and beauty", "Your effort is a seed of future success",
      "You are a person of depth and substance", "Your vulnerability is a mark of bravery", "You are a treasure hidden in plain sight",
      "Your presence brings a sense of calm", "You are a driver of positive change", "Your story is one the world is waiting for",
      "You are a guardian of hope", "Your spirit is as vast as the ocean", "You are a collector of beautiful moments",
      "Your mind is a powerhouse of creativity", "You are a light-bearer in the dark", "Your hand is one that lifts others",
      "You are a dreamer with a practical heart", "Your being is a celebration of life", "You are a catalyst for joy",
      "Your life is an unfolding work of art", "You are a mountain of quiet strength", "Your words have the power to heal",
      "You are a student of life and a master of self", "Your soul is a compass for others", "You are a person of worth beyond measure",
      "Your simple existence is a victory", "You are a light that guides the way", "Your potential is a limitless horizon",
      "Your heart is as wide as the world", "You are a gentle soul with a fierce mind", "Your path is paved with persistence",
      "You are a bright thread in the human story", "Your kindness creates ripples of change", "You are a sanctuary for those in need",
      "Your courage is a silent roar", "You are a reflection of divine creativity", "Your stability is a gift to your community",
      "Your joy is a contagious blessing", "You are a person of purpose and power", "Your integrity is a light that never fades",
      "You are a gift that keeps on giving", "Your presence makes the impossible feel possible", "You are a masterpiece of the present moment",
      "Your light is exactly what the world needs right now"
    ],

    dataAction : [
      "radiating a warmth that heals those around you,", "navigating the world with grace and grit,", "contributing a unique wisdom that only you possess,",
      "moving through life with a heart full of love,", "standing tall in your own authentic truth,", "offering a kindness that changes lives,",
      "growing through every challenge you face,", "building a legacy of compassion and strength,", "shining with a light that inspires others,",
      "walking a path of purpose and meaning,", "embracing the beauty of your own imperfections,", "sharing your gifts with a world that needs them,",
      "believing in the power of your own dreams,", "shaping the future with your every action,", "flowing through life like a river of peace,",
      "showing up every day with courage and heart,", "planting seeds of hope wherever you go,", "transforming obstacles into stepping stones,",
      "living with an integrity that speaks for itself,", "nurturing the light within your own soul,", "carrying the weight of the world with ease,",
      "expressing a creativity that knows no bounds,", "witnessing the beauty in every small moment,", "forging a path of kindness and empathy,",
      "breathing life into every room you enter,", "honoring the sacredness of your own journey,", "rising above the noise with quiet confidence,",
      "teaching the world how to love more deeply,", "cultivating a spirit of joy and resilience,", "inspiring those around you simply by being,",
      "protecting the dreams that live in your heart,", "striving for a better version of yourself,", "holding space for love and understanding,",
      "navigating the unknown with steady faith,", "weaving together a life of deep significance,", "becoming the hero of your own adventure,",
      "offering your unique perspective to the world,", "building bridges of connection and care,", "nurturing the seeds of greatness within,",
      "living a life that is true to your soul,", "shining through the darkness like a beacon,", "demonstrating a strength that is both soft and sure,",
      "pouring your love into everything you do,", "finding the magic in the everyday mundane,", "trusting the timing of your own evolution,",
      "sharing a smile that lifts a heavy heart,", "listening to the whispers of your own intuition,", "creating a ripple of peace in a chaotic world,",
      "walking with a dignity that is inherent,", "exploring the depths of your own potential,", "anchoring yourself in self-belief and hope,",
      "radiating a strength that comes from within,", "blossoming into the person you were meant to be,", "touching lives with your gentle spirit,",
      "fighting for the beauty in your own life,", "crafting a future that reflects your worth,", "finding the silver lining in every cloud,",
      "leading with a heart that is open and brave,", "nurturing the relationships that matter most,", "standing as a pillar of hope and stability,",
      "dreaming with an intensity that changes things,", "acting with a kindness that is revolutionary,", "facing each day with a renewed spirit,",
      "holding onto the light even when it is dim,", "showing the world what it means to be real,", "loving yourself with an unconditional fire,",
      "stewarding the gifts you have been given,", "walking through fire and coming out gold,", "contributing to the collective good of all,",
      "bringing a unique flavor to the human experience,", "transforming your pain into a source of power,", "finding your rhythm in the dance of life,",
      "cultivating a mind that is clear and focused,", "cherishing the life that flows through you,", "standing firm in your own self-worth,",
      "spreading a light that can never be extinguished,", "living each moment with deliberate intention,", "honoring the truth of who you are,",
      "meeting every day with a brave and open face,", "creating beauty out of the simplest things,", "nurturing a heart that is wide and inclusive,",
      "rising to the occasion with quiet power,", "seeking the good in yourself and others,", "building a life that feels like home,",
      "balancing your strength with a tender heart,", "empowering those around you by being you,", "shaping your reality with positive intent,",
      "living as a testament to human resilience,", "offering a hand to those who are struggling,", "trusting the process of your own becoming,",
      "filling the world with your unique vibration,", "carrying a peace that the world cannot take,", "shining even when you are feeling small,",
      "believing in the impossible with every step,", "making your mark with a quiet persistence,", "living out the dreams you once only imagined,",
      "standing as a witness to your own greatness,", "loving the world through your own unique lens,", "growing in ways you never thought possible,",
      "affirming your place in the universe daily,"
    ],

    dataValidation : [
      "which makes you an invaluable part of this world.", "and you are more than worthy of all the love you receive.", "proving that you are exactly where you need to be.",
      "because you were created to make a difference.", "and the world is significantly better because you are in it.", "which is why your presence is so deeply needed.",
      "making you a treasure that deserves to be celebrated.", "and you are loved more than you can possibly imagine.", "which ensures that your life has infinite meaning.",
      "and your contribution to the universe is irreplaceable.", "because you are a miracle in every sense of the word.", "and you deserve to live a life of joy and peace.",
      "which confirms that your worth is truly non-negotiable.", "and you are a necessary light in a world that needs you.", "because you have a purpose that only you can fulfill.",
      "and your journey is one of incredible significance.", "which is a gift to everyone fortunate enough to know you.", "and you are worthy of every good thing that comes your way.",
      "because you are a masterpiece of the highest order.", "and the universe is cheering for your every success.", "which is the most beautiful thing about you.",
      "and you are enough, exactly as you are right now.", "because your very existence is a triumph of life.", "and you possess a strength that is purely your own.",
      "which makes your story one of the most important ever told.", "and you are a beacon of hope for a brighter future.", "because your heart is a place where miracles begin.",
      "and you deserve the same compassion you give to others.", "which is why you are cherished beyond all measure.", "and your potential is as limitless as the stars above.",
      "because you are a light that the world cannot do without.", "and you are a brave and beautiful soul in every way.", "which is proof that your life is a stunning success.",
      "and you are needed here, now, and always.", "because you bring something to life that no one else can.", "and your worth is an inherent part of your being.",
      "which makes you a source of endless inspiration.", "and you are deserving of the most beautiful life imaginable.", "because you are a force for good in a changing world.",
      "and your presence alone is enough to change the world.", "which is why you are loved with an everlasting love.", "and you are a vital piece of the human puzzle.",
      "because your resilience is a gift to the entire world.", "and you are a masterpiece in the eyes of the universe.", "which proves that you are a person of great substance.",
      "and you have the power to create a life you love.", "because you are worth every bit of effort you put into yourself.", "and your light will shine long after the day is done.",
      "which is a beautiful reminder of the power of the human spirit.", "and you are a true and lasting treasure to us all.", "because you are a person of character and heart.",
      "and your existence is a reason for the world to celebrate.", "which makes every step you take a victory in itself.", "and you are a shining example of what is possible.",
      "because you are loved for exactly who you are today.", "and your life is a message of hope to everyone you meet.", "which is why you deserve to be treated with reverence.",
      "and you are a vital heartbeat in the chest of the world.", "because you are a soul of infinite worth and beauty.", "and your path is one that leads to greatness.",
      "which is the ultimate validation of your unique soul.", "and you are a gift that the world is lucky to receive.", "because you are a person of deep and lasting impact.",
      "and your kindness is a light that will never go out.", "which makes you a champion of the human experience.", "and you are worthy of a life that makes you happy.",
      "because your presence is a healing balm for many.", "and you are a necessary part of the unfolding future.", "which is why you are seen, heard, and deeply valued.",
      "and your spirit is a testament to the power of love.", "because you are enough today, tomorrow, and forever.", "and you are a person who truly makes a difference.",
      "which is the most important truth you can ever know.", "and you are loved with a depth you have yet to discover.", "because you are a pioneer of hope and possibility.",
      "and your worth is not measured by what you do, but by who you are.", "which makes you a radiant star in a beautiful sky.", "and you are a beacon of stability in a shifting world.",
      "because you are a creator of joy and a seeker of truth.", "and your soul is a sanctuary for all that is good.", "which is why the world is a better place with you in it.",
      "and you are a person of infinite grace and power.", "because you are a miracle that is still unfolding.", "and your life is a gift of immeasurable value.",
      "which proves that you are a necessary and beautiful soul.", "and you are loved by the universe just for existing.", "because your light is a unique and precious treasure.",
      "and you are worthy of all the wonders that life has to offer.", "which is a truth that will remain forever unchanged.", "and you are a masterpiece of resilience and love.",
      "because your heart is a source of endless hope.", "and you are exactly the person the world needs right now.", "which makes you a stunning reflection of all that is good.",
      "and you are a light-bearer in the journey of life.", "because you are a person of strength, beauty, and worth.", "and your journey is one that is uniquely and beautifully yours.",
      "which is the most powerful thing about your life.", "and you are a necessary part of the great design.", "because you are loved, you are needed, and you are enough.",
      "which is a truth that shines brighter than any star."
    ],

    getRandomSentence () {
      const identityIndex = Math.floor(Math.random() * dataObject.dataIdentity.length);
      const actionIndex = Math.floor(Math.random() * dataObject.dataAction.length);
      const validationIndex = Math.floor(Math.random() * dataObject.dataValidation.length);

      return `${dataObject.dataIdentity[identityIndex]} ${dataObject.dataAction[actionIndex]} ${dataObject.dataValidation[validationIndex]}`;
    }
};