
const inspirationalList = [
  "No one can make you feel inferior without your consent. - Eleanor Roosevelt",
  "To the world you may be one person, but to one person you may be the world. - Dr. Seuss",
  "You are loved just for being who you are, just for existing. - Ram Dass",
  "Your existence is proof that this world needed you. - Unknown",
  "You are the only person who can use your ability. It is an awesome responsibility. - Zig Ziglar",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
  "You are enough just as you are. Each emotion, each thought, and each breath is a gift. - Unknown",
  "The world is better because you are in it. Never forget that your presence matters. - Unknown",
  "You were born to be real, not to be perfect. You are worthy of love in your most natural state. - Unknown",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
  "You are not a drop in the ocean. You are the entire ocean in a drop. - Rumi",
  "Your value does not decrease based on someone's inability to see your worth. - Unknown",
  "Owning our story and loving ourselves through that process is the bravest thing that we’ll ever do. - Brené Brown",
  "You are a once-in-a-lifetime cosmic event. The universe spent billions of years preparing for your arrival. - Unknown",
  "You don't have to be 'useful' to be worthy of space. Your breath alone is enough. - Unknown",
  "The way you treat yourself sets the standard for others. Treat yourself with the reverence you deserve. - Sonya Renee Taylor",
  "There is a crack in everything, that's how the light gets in. Your flaws are your brilliance. - Leonard Cohen",
  "You are the only you there is, and that is your superpower. Embrace the uniqueness only you provide. - Unknown",
  "Your voice is needed in a world that often stays silent. Speak your truth, for it has value. - Unknown",
  "Love yourself first and everything else falls into line. You really have to love yourself to get anything done in this world. - Lucille Ball",
  "Self-care is never a selfish act—it is simply good stewardship of the only gift I have. - Parker Palmer",
  "You are a work of art and a work in progress, all at the same time. Enjoy the process of becoming. - Unknown",
  "Whatever you are, be a good one. You have something to contribute that no one else can. - Abraham Lincoln",
  "You are braver than you believe, stronger than you seem, and smarter than you think. - A.A. Milne",
  "The most beautiful thing you can wear is confidence in who you were created to be. - Blake Lively",
  "Don’t let the noise of others’ opinions drown out your own inner voice. You know your worth better than anyone. - Steve Jobs",
  "Act as if what you do makes a difference. It does. - William James",
  "Your life is your message to the world. Make sure it's inspiring. - Unknown",
  "In a world where you can be anything, be kind to yourself. You deserve your own affection. - Unknown",
  "You are needed. There is a hole in the universe that only you can fill. - Unknown",
  "Be yourself; everyone else is already taken. Your authentic self is your greatest contribution. - Oscar Wilde",
  "A person’s a person, no matter how small. Your impact is not measured by your size. - Dr. Seuss",
  "You are not your mistakes; you are the person who survived them. That resilience is beautiful. - Unknown",
  "If you want to lift yourself up, lift up someone else. You have the power to change a life. - Booker T. Washington",
  "Your heart is a masterpiece. Treat it with the kindness and respect a masterpiece deserves. - Unknown",
  "The world needs your light, your soul, and your unique way of being. Don't hide it away. - Unknown",
  "You were not made to fit in. You were made to stand out and bring your own flavor to life. - Unknown",
  "Love is the great miracle cure. Loving ourselves works miracles in our lives. - Louise Hay",
  "The only person you should try to be better than is the person you were yesterday. - Matty Mullins",
  "You carry so much love in your heart. Give some to yourself today. - Unknown",
  "Every soul is a melody. Your particular song is one the world has been waiting to hear. - Unknown",
  "You are worthy of the time it takes to find yourself. Don't rush the discovery of your greatness. - Unknown",
  "Do not settle for a version of yourself that is less than the one you truly are. - Unknown",
  "Your purpose is not just to produce, but to be. Your existence is a success story. - Unknown",
  "Everything you need is already inside you. The world is just waiting for you to realize it. - Unknown",
  "The things that make you different are the things that make you. Celebrate your individuality. - Unknown",
  "You have been criticizing yourself for years, and it hasn't worked. Try approving of yourself and see what happens. - Louise Hay",
  "The most creative act you will ever undertake is the act of creating yourself. - Unknown",
  "You are more than enough. You are a treasure, a light, and a necessity. - Unknown",
  "Don't trade your authenticity for approval. Your worth is not up for negotiation. - Unknown",
  "Kindness begins with the self. You cannot pour from an empty cup. - Unknown",
  "The world is changed by your example, not by your opinion. Your life is an example of resilience. - Paulo Coelho",
  "You are the architect of your own happiness. Build something beautiful with the love you have. - Unknown",
  "True belonging only happens when we present our authentic, imperfect selves to the world. - Brené Brown",
  "Your potential is like a seed; with self-love, it will grow into something magnificent. - Unknown",
  "There is nothing more beautiful than someone who goes out of their way to make life beautiful for others. - Unknown",
  "You are significant. You are important. You are loved. - Unknown",
  "The sun does not compare itself to the moon; they both shine when it is their time. - Unknown",
  "Trust yourself. You have survived every hard day of your life so far. - Unknown",
  "Your inner peace is your greatest wealth. Protect it with the boundary of self-worth. - Unknown",
  "You are capable of more than you know. Don't let fear tell you otherwise. - Unknown",
  "The world is waiting for your specific brand of magic. No one else can do what you do. - Unknown",
  "Your value is inherent. It was given to you at birth and cannot be taken away. - Unknown",
  "Sometimes the most important thing in a whole day is the rest we take between two deep breaths. - Etty Hillesum",
  "You are the artist of your own life. Don't give the paintbrush to anyone else. - Unknown",
  "Every small step you take is a victory. Celebrate your progress, no matter how minor. - Unknown",
  "You are a gift to those who know you. Your kindness leaves a lasting mark. - Unknown",
  "Believe that you are worthy of good things, and they will find their way to you. - Unknown",
  "Your perspective is a vital piece of the human puzzle. Without you, the picture is incomplete. - Unknown",
  "Beauty begins the moment you decide to be yourself. - Coco Chanel",
  "You are enough. You have enough. You do enough. - Unknown",
  "Hold your head high. The universe put the stars in the sky, but it put the soul in you. - Unknown",
  "Your sensitivity is a strength. It allows you to feel the world in a way others cannot. - Unknown",
  "You are the sum of all the love you have ever given and received. That is a vast wealth. - Unknown",
  "Don't be afraid to take up space. You were meant to be here. - Unknown",
  "There is a power in your gentleness. Never mistake your kindness for weakness. - Unknown",
  "You deserve the same compassion that you so readily give to everyone else. - Unknown",
  "Your journey is unique, and that is what makes it beautiful. Don't compare your Chapter 1 to someone else's Chapter 20. - Unknown",
  "You are stronger than the things that tried to break you. Your scars are medals of honor. - Unknown",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
  "You are the miracle you've been waiting for. Everything starts with you. - Unknown",
  "Never apologize for having high standards. You deserve the best life has to offer. - Unknown",
  "Your mind is a garden; plant seeds of self-belief and watch them bloom. - Unknown",
  "You are not a burden. You are a human being with needs, and those needs are valid. - Unknown",
  "The world needs people who have come alive. Go do what makes you come alive. - Howard Thurman",
  "You have a heart of gold. Don't let the world make it cold. - Unknown",
  "The best version of you is the one that is happy. Focus on your joy. - Unknown",
  "You belong here. Every atom in your body belongs to the stars. - Unknown",
  "Your worth is not defined by your productivity. You are valuable even when you are still. - Unknown",
  "You are the light of the world. Even in the darkness, your flicker matters. - Unknown",
  "Be patient with yourself. Self-growth is tender; it’s holy ground. - Stephen Covey",
  "You are a lighthouse. Your stability and light help others find their way home. - Unknown",
  "There is nobody like you, and that is your greatest asset. - Unknown",
  "You are deserving of a life that makes you feel excited to wake up. - Unknown",
  "The love you are looking for is already within you. You are your own best friend. - Unknown",
  "Your life has meaning, even on the days when you can't see it. - Unknown",
  "You are a force of nature. Gentle as a breeze, yet capable of moving mountains. - Unknown",
  "Never forget that you are a miracle. The odds of you existing are nearly zero, yet here you are. - Unknown",
  "You are worthy of being known and deeply loved. Don't settle for anything less. - Unknown",
  "Your story is still being written. The best chapters are yet to come. - Unknown"
];


//export default inspirationalList;




// another way to do this is to export the function directly
//export const getInspirationalQuotes = (index = Math.floor(Math.random() * inspirationalList.length)) => inspirationalList[index];
